iod_poc_datasets:
  tables:
    - always_keep_pk_fk: True
    - max_concurrent_vector_calls: 20
    - table_top_k: 7
    - table_score_threshold: 0.2
    - rrf_k: 60
  columns:
    - column_top_k_per_entity: 10
    - column_score_threshold: 0.2
    - min_columns_to_keep_table: 2 
  entities:
    - value_top_k: 5
    - value_score_threshold: 0.2