"""Architecture contracts and context models for graph generation."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol

import pandas as pd
import plotly.graph_objects as go

from .utils import ColumnProfile


@dataclass(frozen=True)
class GraphContext:
    df: pd.DataFrame
    profile: ColumnProfile


class GraphStrategy(Protocol):
    name: str

    def build(self, context: GraphContext, composer: "FigureComposer") -> go.Figure:
        """Build a chart figure for this strategy."""


class FigureComposer(Protocol):
    def build_gauge(self, context: GraphContext) -> go.Figure: ...
    def build_scatter(self, context: GraphContext) -> go.Figure: ...
    def build_bar(self, context: GraphContext) -> go.Figure: ...
    def build_horizontal_bar(self, context: GraphContext) -> go.Figure: ...
    def build_line(self, context: GraphContext) -> go.Figure: ...
    def build_area(self, context: GraphContext) -> go.Figure: ...
    def build_pie(self, context: GraphContext, hole: float) -> go.Figure: ...
    def build_pareto(self, context: GraphContext) -> go.Figure: ...
    def build_funnel(self, context: GraphContext) -> go.Figure: ...
    def build_waterfall(self, context: GraphContext) -> go.Figure: ...
    def build_combo_bar_line(self, context: GraphContext) -> go.Figure: ...
    def build_grouped_bar(self, context: GraphContext) -> go.Figure: ...
    def build_stacked_bar(self, context: GraphContext) -> go.Figure: ...
    def build_treemap(self, context: GraphContext) -> go.Figure: ...
    def build_sunburst(self, context: GraphContext) -> go.Figure: ...
